#!/bin/bash

ffmpeg -f avi -r 29.97 -vcodec copy -vtag XVID -s 704x384 -aspect 16:9 -maxrate 1800k -b 1500k -qmin 3 -qmax 5 -bufsize 4096 -mbd 2 -bf 2 -flags +4mv -trellis -aic -cmp 2 -subcmp 2 -g 300 -acodec copy -ar 48000 -ab 128k -ac 2 -i "$1" -o "$2"
