#!/usr/bin/env bash

thisCommandName=$(echo $0 | awk -F/ '{print $NF}' | cut -c6-)
touchpad_id=$(xinput list | grep TouchPad | grep -o 'id=[[:alnum:]]*' | cut -d "=" -f 2)
#touchpad_id=$(xinput list --id-only "AlpsPS/2 ALPS DualPoint TouchPad")

if [ $thisCommandName == "enable" ]; then
	echo "enable...."
	xinput enable $touchpad_id
else
	echo "disable...."
	xinput disable $touchpad_id
fi

echo "TouchPad's id = $touchpad_id : $thisCommandName"

#xinput set-prop "AlSynPS/2 Synaptics TouchPad" "Device Enabled" 1


